#!/usr/bin/env node
// ============================================
// THE 1969 Bot - Easy Setup
// ============================================
// Interactive setup - just paste your cookies
//
// Usage: npm run setup

import { createInterface } from "readline";
import { writeFileSync, existsSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const rl = createInterface({
  input: process.stdin,
  output: process.stdout,
});

function question(prompt: string): Promise<string> {
  return new Promise((resolve) => rl.question(prompt, (answer) => resolve(answer as string)));
}

function extractCookie(input: string): string {
  // Handle various formats:
  // 1. Just the JWT: eyJhbGci...
  // 2. Full cookie: the1969_session=eyJhbGci...
  // 3. Multiple cookies: the1969_session=eyJhbGci...; other=value
  
  input = input.trim();
  
  // If it's just the JWT (starts with eyJ)
  if (input.startsWith("eyJ")) {
    return `the1969_session=${input}`;
  }
  
  // If it contains the1969_session
  if (input.includes("the1969_session=")) {
    const match = input.match(/the1969_session=([^;]+)/);
    if (match) {
      return `the1969_session=${match[1].trim()}`;
    }
  }
  
  // Otherwise assume it's the full cookie string
  return input;
}

function extractUsername(cookie: string): string | null {
  // Try to decode JWT to get username
  try {
    const jwt = cookie.replace("the1969_session=", "");
    const parts = jwt.split(".");
    if (parts.length >= 2) {
      const payload = JSON.parse(Buffer.from(parts[1], "base64").toString());
      return payload.x || null;
    }
  } catch (e) {
    // Ignore decode errors
  }
  return null;
}

console.log(`
╔═══════════════════════════════════════╗
║   THE 1969 Bot - Easy Setup           ║
╚═══════════════════════════════════════╝

This will create your .env file.
You just need to paste your cookie(s).

How to get your cookie:
1. Go to https://the1969.io and login
2. Press F12 (DevTools)
3. Go to Application > Cookies
4. Copy the value of "the1969_session"
   (or just copy the whole cookie string)

`);

async function main() {
  const accounts = [];
  
  while (true) {
    const num = accounts.length + 1;
    console.log(`\n--- Account #${num} ---`);
    
    const cookie = await question(
      `Paste cookie (or press Enter to ${accounts.length > 0 ? "finish" : "skip"}): `
    );
    
    if (!cookie.trim()) {
      if (accounts.length === 0) {
        console.log("\n❌ You need at least 1 account. Try again.\n");
        continue;
      }
      break;
    }
    
    const cleaned = extractCookie(cookie);
    const username = extractUsername(cleaned);
    
    let name = await question(
      `Account name (default: ${username || `account${num}`}): `
    );
    name = name.trim() || username || `account${num}`;
    
    accounts.push({ name, cookie: cleaned });
    console.log(`✓ Added: ${name}`);
    
    const more = await question("\nAdd another account? (y/N): ");
    if (!more.trim().toLowerCase().startsWith("y")) {
      break;
    }
  }
  
  rl.close();
  
  if (accounts.length === 0) {
    console.log("\n❌ No accounts added. Exiting.\n");
    process.exit(1);
  }
  
  // Generate .env
  const envContent = `# THE 1969 Bot Configuration
# Auto-generated by setup script

ACCOUNTS=${JSON.stringify(accounts)}
PROXIES=[]

POLL_INTERVAL=15000
ENABLE_AUTO_CLAIM=true
ENABLE_TASK_CLAIM=true
`;
  
  const envPath = join(__dirname, "..", ".env");
  
  if (existsSync(envPath)) {
    const overwrite = await new Promise((resolve) => {
      const rl2 = createInterface({
        input: process.stdin,
        output: process.stdout,
      });
      rl2.question("\n⚠️  .env already exists. Overwrite? (y/N): ", (answer) => {
        rl2.close();
        resolve(answer.trim().toLowerCase().startsWith("y"));
      });
    });
    
    if (!overwrite) {
      console.log("\n❌ Setup cancelled. Your existing .env was not modified.\n");
      process.exit(0);
    }
  }
  
  writeFileSync(envPath, envContent);
  
  console.log(`
╔═══════════════════════════════════════╗
║   ✓ Setup Complete!                   ║
╚═══════════════════════════════════════╝

Created .env with ${accounts.length} account(s):
${accounts.map((a) => `  • ${a.name}`).join("\n")}

Next steps:
  npm start       - Run the bot
  npm run auth    - Test authentication
  npm run status  - Check drop status

The bot will:
1. Auto-apply for pre-whitelist
2. Auto-claim drops once approved
3. Auto-complete social tasks

Press Ctrl+C to stop the bot anytime.
`);
}

main().catch((e) => {
  console.error("\n❌ Error:", e.message);
  process.exit(1);
});
